# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 614c98b769dec1d300e793bf8d8a2e8f74d7111df131191b62ab3f3753c61ec07a051c9a710b0cd06f7ead5156b20ceda6763f0e4a346b401a8576ebad9a1e9b

test:
  secret_key_base: 6eea558447a34205d989ab9dc05e490fdd966b4647adfaa9a5194147d91c7708844665e68fda54639de92c00b31fc6c9f3a35c9287de4d47b176b15c8e3369a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
